name: Test for Rust

on:
  push:
    paths:
      - "**/*.rs"
      - ".github/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup rustfmt
        run: rustup component add rustfmt
      - name: Run fmt
        run: cargo fmt --all -- --check
      - name: Setup clippy
        run: rustup component add clippy
      - name: Run clippy
        run: cargo clippy -- -D warnings
      - name: Run tests
        run: cargo test --verbose
      - name: Build
        run: cargo build --verbose
      - name: Setup wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Build wasm
        working-directory: wasm
        run: wasm-pack build --target web
